// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Answer$ReactTemplate = require("../src/Answer.bs.js");

Jest.describe("Answer", (function (param) {
        Jest.describe("contains", (function (param) {
                Jest.test("it does contain", (function (param) {
                        return Jest.Expect.toBe(true, Jest.Expect.expect(Answer$ReactTemplate.contains(Curry._1(Answer$ReactTemplate.make, "test"), "test")));
                      }));
                return Jest.test("it doesn't contain", (function (param) {
                              return Jest.Expect.toBe(false, Jest.Expect.expect(Answer$ReactTemplate.contains(Curry._1(Answer$ReactTemplate.make, "test"), "something else")));
                            }));
              }));
        return Jest.describe("get", (function (param) {
                      Jest.test("it retrieves an item", (function (param) {
                              return Jest.Expect.toBe("test", Jest.Expect.expect(Answer$ReactTemplate.get(Curry._1(Answer$ReactTemplate.make, "test"))));
                            }));
                      return Jest.test("it retrieves empty from an empty set", (function (param) {
                                    return Jest.Expect.toBe("", Jest.Expect.expect(Answer$ReactTemplate.get(Answer$ReactTemplate.empty)));
                                  }));
                    }));
      }));

/*  Not a pure module */
